"""Detection rules for the PQC migration scanner.

Each rule is a dict with:
  id            short stable identifier, used in inventory output
  name          human readable name
  category      one of: asymmetric, signatures, tls, hash, certificates,
                hsm, config, experimental, pq_ready
  algorithm     the algorithm or primitive detected
  regexes       list of regular expressions (case sensitive unless noted)
  file_types    list of file extensions or name markers this rule applies to.
                Markers: "Dockerfile" matches any file whose name starts with
                Dockerfile; ".env" matches any file with .env in its name.
  severity      critical, high, medium, low, or info
  description   why this matters for PQC migration
  guidance      what NIST or industry guidance says about it
"""

PATTERNS = [
    {
        "id": "RSA_KEYGEN",
        "name": "RSA key generation",
        "category": "asymmetric",
        "algorithm": "RSA",
        "regexes": [
            r"RSA\.generate\s*\(",
            r"rsa\.newkeys\s*\(",
            r"generate_private_key\s*\(\s*rsa",
            r"openssl\s+genrsa",
        ],
        "file_types": [".py", ".sh"],
        "severity": "critical",
        "description": "RSA key material is created here. RSA is broken by Shor's algorithm on a cryptographically relevant quantum computer.",
        "guidance": "NIST IR 8547: RSA deprecated after 2030, disallowed after 2035. Plan migration to ML-KEM for key establishment.",
    },
    {
        "id": "RSA_USE",
        "name": "RSA encryption or key wrapping in use",
        "category": "asymmetric",
        "algorithm": "RSA",
        "regexes": [
            r"PKCS1_OAEP",
            r"PKCS1_v1_5",
            r"PKCS1_PSS",
            r"RSA\.construct\s*\(",
            r"rsa\.encrypt\s*\(",
            r"rsa\.decrypt\s*\(",
        ],
        "file_types": [".py"],
        "severity": "critical",
        "description": "RSA is used for encryption or key wrapping. Ciphertext captured today can be decrypted later (harvest now, decrypt later).",
        "guidance": "Prioritize by data secrecy lifetime. Migrate key establishment to ML-KEM, ideally in a hybrid construction during transition.",
    },
    {
        "id": "ECDSA_USE",
        "name": "Elliptic curve signatures or key agreement",
        "category": "asymmetric",
        "algorithm": "ECDSA/ECDH",
        "regexes": [
            r"ecdsa\.SigningKey",
            r"ecdsa\.VerifyingKey",
            r"SECP256k1",
            r"SECP256K1",
            r"SECP256R1",
            r"secp256k1",
            r"ec\.SECP256R1",
            r"ec\.SECP384R1",
            r"generate_private_key\s*\(\s*ec\.",
            r"ECDH",
            r"X25519",
        ],
        "file_types": [".py", ".yaml", ".yml", ".env", ".json", ".toml"],
        "severity": "critical",
        "description": "Elliptic curve cryptography (signatures or Diffie-Hellman) is in use. ECC falls to Shor's algorithm, likely before RSA at equivalent classical strength.",
        "guidance": "Migrate signatures to ML-DSA and key agreement to ML-KEM. Note: X25519 is classical ECDH, not post-quantum.",
    },
    {
        "id": "DSA_DH_USE",
        "name": "DSA or classic Diffie-Hellman",
        "category": "asymmetric",
        "algorithm": "DSA/DH",
        "regexes": [
            r"\bDSA\.generate",
            r"dsa\.generate",
            r"DiffieHellman",
            r"DH_generate",
        ],
        "file_types": [".py"],
        "severity": "critical",
        "description": "Classic DSA or Diffie-Hellman is in use. Both rely on the discrete logarithm problem broken by Shor's algorithm.",
        "guidance": "Replace with ML-KEM (key establishment) or ML-DSA (signatures) per FIPS 203/204.",
    },
    {
        "id": "JWT_ALG",
        "name": "JWT signed with classical algorithm",
        "category": "signatures",
        "algorithm": "JWT/RS256/ES256",
        "regexes": [
            r"jwt\.encode\s*\([^)]*RS256",
            r"jwt\.encode\s*\([^)]*ES256",
            r"jwt\.encode\s*\([^)]*HS256",
            r"['\"]RS256['\"]",
            r"['\"]ES256['\"]",
            r"\bRS256\b",
            r"\bES256\b",
        ],
        "file_types": [".py", ".yaml", ".yml", ".json", ".env", ".toml", ".cfg", ".ini"],
        "severity": "high",
        "description": "JWTs are signed with RSA (RS256) or ECDSA (ES256). Tokens issued today can be forged once a quantum computer breaks the signing key.",
        "guidance": "Plan migration of token signing to ML-DSA. Track token lifetimes: long-lived refresh tokens are the priority.",
    },
    {
        "id": "TLS_VERSION",
        "name": "Legacy TLS version configured",
        "category": "tls",
        "algorithm": "TLS 1.2 and below",
        "regexes": [
            r"PROTOCOL_TLSv1_2",
            r"PROTOCOL_TLSv1\b",
            r"PROTOCOL_SSLv23",
            r"tls_min_version.{0,20}1\.2",
            r"TLS-1-2",
            r"TLSv1\.2",
            r"min_tls_version.{0,20}1\.2",
        ],
        "file_types": [".py", ".yaml", ".yml", ".tf", ".env", ".json"],
        "severity": "high",
        "description": "TLS 1.2 or older is pinned. Even with TLS 1.3, classical key exchange must be upgraded; pinning old versions blocks hybrid post-quantum handshakes.",
        "guidance": "Move to TLS 1.3 with hybrid post-quantum key exchange (RFC 10024 standardizes this). IETF has not yet standardized PQ authentication.",
    },
    {
        "id": "CIPHER_STRING",
        "name": "Classical cipher suite string",
        "category": "tls",
        "algorithm": "RSA/ECDSA cipher suites",
        "regexes": [
            r"ECDHE-RSA",
            r"ECDHE-ECDSA",
            r"DHE-RSA",
            r"AES128-SHA\b",
            r"\bDES\b",
            r"3DES",
            r"\bRC4\b",
        ],
        "file_types": [".py", ".yaml", ".yml", ".env", ".tf"],
        "severity": "high",
        "description": "Cipher suite strings reference RSA or ECDSA key exchange. These suites cannot negotiate post-quantum key exchange.",
        "guidance": "Inventory cipher configuration as part of the CBOM. Cipher agility is a prerequisite for hybrid deployment.",
    },
    {
        "id": "WEAK_HASH_MD5",
        "name": "MD5 in use",
        "category": "hash",
        "algorithm": "MD5",
        "regexes": [
            r"hashlib\.md5",
            r"\bmd5\s*\(",
            r"MD5SUM",
        ],
        "file_types": [".py", ".sh"],
        "severity": "medium",
        "description": "MD5 is cryptographically broken for collision resistance. Not a quantum issue, but a hygiene finding that belongs in the same remediation pass.",
        "guidance": "Replace with SHA-256 or SHA-384. Low effort, do it during crypto-agility work.",
    },
    {
        "id": "WEAK_HASH_SHA1",
        "name": "SHA-1 in use",
        "category": "hash",
        "algorithm": "SHA-1",
        "regexes": [
            r"hashlib\.sha1",
            r"hmac\.new\s*\([^)]*hashlib\.sha1",
            r"HMAC-SHA1",
            r"\bsha1\s*\(",
        ],
        "file_types": [".py"],
        "severity": "medium",
        "description": "SHA-1 is deprecated for digital signatures and collision-sensitive uses. Hygiene finding for the same remediation pass.",
        "guidance": "Replace with SHA-256 or SHA-384. Note: SHA-2 and SHA-3 are considered quantum-safe for hashing.",
    },
    {
        "id": "CERT_RSA",
        "name": "RSA certificate or private key material",
        "category": "certificates",
        "algorithm": "RSA X.509",
        "regexes": [
            r"BEGIN RSA PRIVATE KEY",
            r"BEGIN PRIVATE KEY",
            r"load_verify_locations",
            r"load_cert_chain",
            r"\.crt\b",
            r"\.pem\b",
            r"server\.key",
            r"CERT_PATH",
        ],
        "file_types": [".py", ".pem", ".crt", ".key", ".env", "Dockerfile", ".yaml", ".yml"],
        "severity": "high",
        "description": "RSA certificate or private key material is referenced. A 2026 study of 32,011 domains found zero hybrid post-quantum certificates deployed: the certificate layer is the long pole of migration.",
        "guidance": "Track every certificate in the CBOM with issuer, expiry, and algorithm. Plan for post-quantum or hybrid certificates as browser root programs and CAs (e.g., Cloudflare's Merkle Tree Certificates, targeted Q1 2027) make them available.",
    },
    {
        "id": "HSM_REF",
        "name": "HSM or PKCS#11 reference",
        "category": "hsm",
        "algorithm": "HSM/PKCS#11",
        "regexes": [
            r"pkcs11",
            r"PKCS11",
            r"PKCS#11",
            r"\bHSM\b",
            r"SoftHSM",
            r"CloudHSM",
            r"LunaSA",
        ],
        "file_types": [".py", ".yaml", ".yml", ".env", "Dockerfile"],
        "severity": "high",
        "description": "Hardware security module usage detected. HSM firmware and vendor support are repeatedly cited as the long pole of PQC migration.",
        "guidance": "Confirm PQC algorithm support and firmware roadmap with the HSM vendor early. Vendor lag is a top reported obstacle.",
    },
    {
        "id": "HARDCODED_ALG",
        "name": "Hardcoded algorithm selection in config",
        "category": "config",
        "algorithm": "various",
        "regexes": [
            r"jwt_algorithm\s*:\s*\S+",
            r"kms_key_type\s*:\s*\S+",
            r"signing_curve\s*:\s*\S+",
            r"SIGNING_KEY_TYPE\s*=\s*\S+",
            r"JWT_ALG\s*=\s*\S+",
            r"KEY_TYPE\s*=\s*\S+",
            r"ALGORITHM\s*=\s*\S+",
        ],
        "file_types": [".yaml", ".yml", ".env", ".json", ".toml", ".cfg", ".ini", ".tf"],
        "severity": "medium",
        "description": "Algorithm choice is hardcoded in configuration. This is the opposite of crypto-agility: every migration requires a code or config change per service.",
        "guidance": "Move algorithm selection behind an abstraction that can be changed without redeploying application logic. Crypto-agility should be a funded workstream from year one.",
    },
    {
        "id": "OPENSSL_LEGACY",
        "name": "Legacy OpenSSL pinned",
        "category": "config",
        "algorithm": "OpenSSL 1.1",
        "regexes": [
            r"openssl1\.1",
            r"openssl-1\.1",
            r"OpenSSL_1_1",
            r"libssl1\.1",
        ],
        "file_types": ["Dockerfile", ".txt", ".yaml", ".yml"],
        "severity": "medium",
        "description": "OpenSSL 1.1 is pinned. PQC-capable providers (including OQS integrations) target OpenSSL 3.x. The old version blocks migration.",
        "guidance": "Upgrade to OpenSSL 3.x as a prerequisite for hybrid post-quantum TLS testing.",
    },
    {
        "id": "FNDSA_EXPERIMENTAL",
        "name": "FN-DSA (Falcon) experimental use",
        "category": "experimental",
        "algorithm": "FN-DSA",
        "regexes": [
            r"\bFalcon\b",
            r"falcon-512",
            r"falcon-1024",
            r"FN-DSA",
            r"FNDSA",
        ],
        "file_types": [".py", ".yaml", ".yml", ".env"],
        "severity": "medium",
        "description": "FN-DSA is still in draft (prospective FIPS 206, expected late 2026 or early 2027). Its Gaussian sampler has known side-channel concerns. DO NOT DEPLOY in production yet.",
        "guidance": "Track for future evaluation. Prefer finalized ML-DSA for near-term signature migration.",
    },
    {
        "id": "PQC_READY",
        "name": "Post-quantum algorithm already present",
        "category": "pq_ready",
        "algorithm": "ML-KEM/ML-DSA",
        "regexes": [
            r"ML-KEM",
            r"ml_kem",
            r"\bKyber\b",
            r"ML-DSA",
            r"ml_dsa",
            r"\bDilithium\b",
            r"X25519MLKEM768",
        ],
        "file_types": [".py", ".yaml", ".yml", ".env", ".json"],
        "severity": "info",
        "description": "A NIST-standardized post-quantum algorithm is already referenced. Good news: this surface is on the quantum-safe path.",
        "guidance": "Verify it is actually exercised (not just imported) and record it in the CBOM as migrated or in-progress.",
    },
]

CATEGORIES = sorted({p["category"] for p in PATTERNS})
